<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */

header('Content-type: text/html');
header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


function jungle_product_init() // init function called by defaulted when this module loaded by system
{

    //echo $GLOBALS['theme'];
    //echo 5656;
    //echo user_authenticate('debasis','Pp@ss1234');

//echo "kl";
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



}

function jungle_product_menu()
{
    $items = array();

    $items['imguploadproduct'] = array(
        'title' => 'Add jungleproduct',
        'page callback' => 'imguploadproduct',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );


    $items['addjungleproduct'] = array(
        'title' => 'Add jungleproduct',
        'page callback' => 'addjungleproduct',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    $items['jungleproductlist'] = array(
        'title' => 'jungleproduct List',
        'page callback' => 'jungleproductlist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['parentproductlist'] = array(
        'title' => 'parent product List',
        'page callback' => 'parentproductlist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    $items['deletejungleproduct'] = array(
        'title' => 'jungleproduct Delete',
        'page callback' => 'deletejungleproduct',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
   $items['jungleproductdetails'] = array(
        'title' => 'jungleproduct details',
        'page callback' => 'jungleproductdetails',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['jungleproductupdates'] = array(
        'title' => 'jungleproduct Updates',
        'page callback' => 'jungleproductupdates',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    $items['jungleproductupdatestatus'] = array(
        'title' => 'jungleproduct Updates Status',
        'page callback' => 'jungleproductupdatestatus',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['uploadjungleproductimage'] = array(
        'title' => 'jungleproduct File Upload',
        'page callback' => 'uploadjungleproductimage',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['filedownload'] = array(
        'title' => 'jungleproduct File Upload',
        'page callback' => 'filedownload',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );



    return $items;
}


function imguploadproduct(){


    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    set_time_limit(0);

    $x=arg();
    //print_r($x[1]);

    $queryu = db_select('jungleproduct', 'ca');
    $queryu->fields('ca');
    $queryu->condition('ca.id',$x[1],'=');
    $resultu = $queryu->execute();

    ini_set('memory_limit', '128M');

    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {
            $temparray=$recordu;
             $filePath = image_style_url('front-photo_600_600_', (@$recordu['product_file']));

            $jungleproductlist[$i]= $temparray;
            $i++;

            /*            $jungleproductlist[$i]['cat_name'] = $recordu['cat_name'];
                        $jungleproductlist[$i]['id'] = $recordu['id'];
                        $jungleproductlist[$i]['parent_cat'] = $recordu['parent_cat'];
                        $jungleproductlist[$i]['status'] = $recordu['status'];
                        $i++;*/

        }
    }


    //print_r($filePath);
    //exit;







    // Load the stamp and the photo to apply the watermark to
    $stamp = imagecreatefrompng('http://testbed.jungledrones.com/images/icon_1.png');
    if(strpos($filePath,'.png')>0)$im = imagecreatefrompng($filePath);
    if(strpos($filePath,'.jpg')>0) $im = imagecreatefromjpeg($filePath);
    if(strpos('.jpeg',$filePath)>0) $im = imagecreatefromjpeg($filePath);

    //list($current_width, $current_height) = getimagesize($filePath);



// Set the margins for the stamp and get the height/width of the stamp image
    $marge_right = 0;
    $marge_bottom = 0;
    $sx = imagesx($stamp);
    $sy = imagesy($stamp);
    $imgx = imagesx($im);
    $imgy = imagesy($im);
    $centerX=round($imgx/2);
    $centerY=round($imgy/2);

// Copy the stamp image onto our photo using the margin offsets and the photo
// width to calculate positioning of the stamp.
    //imagecopy($im, $stamp, imagesx($im) - $sx - $marge_right, imagesy($im) - $sy - $marge_bottom, 0, 0, imagesx($stamp), imagesy($stamp));
    //imagecopy($im, $stamp, $centerX, $centerY, 0, 0, imagesx($stamp), imagesy($stamp));
    imagecopy($im, $stamp, 0, -150,0, 0, imagesx($stamp), imagesy($stamp));

// Output and free memory
    header('Content-type: image/png');
    imagepng($im);
    imagedestroy($im);


}

function uploadjungleproductimage(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    set_time_limit(0);

    $target_dir = realpath(dirname(__FILE__))."/uploads/";
    $path_parts = pathinfo($_FILES['Filedata']['name']);
    $filename = rand().'_'.time().'.'.$path_parts['extension'];
    ini_set('memory_limit', '128M');

    $profile_url = '';
    $extarray=array('jpg','png','gif','mp4');
    if(in_array($path_parts['extension'],$extarray)) {
        if (move_uploaded_file($_FILES["Filedata"]["tmp_name"], $target_dir . $filename)) {
            //$account = user_load($_POST['userid']);

            $filepath = ($target_dir . $filename);

            $file = (object)array(
                'uid' => 1,
                'uri' => $filepath,
                'filemime' => file_get_mimetype($filepath),
                'status' => 1,
            );
            if ($file) {
// Move the file, into the Drupal file system
                if ($file = file_move($file, 'public://')) {
                    $file->status = FILE_STATUS_PERMANENT;
                    // $file->file_display = 1;
                    $file = file_save($file);
                    //set the extra values needed to make node_save work
                    $file->display = 1;
                    $file->description = "";
                }

            }
        }
      // echo file_create_url(@$file->uri);
//print_r($file);
        if($path_parts['extension']=='mp4'){
            $data['video_url'] = file_create_url(@$file->uri);;
        }
        else{
            $data['image_url'] = image_style_url('large', (@$file->uri));
        }
        //

        $data['image_name'] = (@$file->uri);
        // $data['status'] = 'success';
    }
    else{
        $data['status']='error';
    }
    echo json_encode(@$data) ;
}
function jungleproductdetails(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $queryu = db_select('jungleproduct', 'jd');
    ini_set('memory_limit', '128M');
    $queryu->innerJoin('junglecategory', 'jc','jc.id=jd.category_id');
    $queryu->fields('jd');
    $queryu->fields('jc',array('type'))
        ->condition('jd.id', $_POST['id'], '=');
    $resultu = $queryu->execute();

    while($recordu = $resultu->fetchAssoc()) {
        $temparray=$recordu;

        if($recordu['product_file']!=''){
            $productextns=explode('.',$recordu['product_file']);

            if($productextns['1']=='mp4'){
                $temparray['video_url'] = file_create_url(@$recordu['product_file']);;
            }
            else{
                $temparray['image_url'] = image_style_url('large', (@$recordu['product_file']));

                $stamp = imagecreatefrompng('http://testbed.jungledrones.com/images/icon5copy.png');
                $im = imagecreatefrompng($temparray['image_url']);

// Set the margins for the stamp and get the height/width of the stamp image
                $marge_right = 0;
                $marge_bottom = 0;
                $sx = imagesx($stamp);
                $sy = imagesy($stamp);
                $imgx = imagesx($im);
                $imgy = imagesy($im);
                $centerX=round($imgx/2);
                $centerY=round($imgy/2);

// Copy the stamp image onto our photo using the margin offsets and the photo
// width to calculate positioning of the stamp.
                //imagecopy($im, $stamp, imagesx($im) - $sx - $marge_right, imagesy($im) - $sy - $marge_bottom, 0, 0, imagesx($stamp), imagesy($stamp));
                //imagecopy($im, $stamp, $centerX, $centerY, 0, 0, imagesx($stamp), imagesy($stamp));
                imagecopy($im, $stamp, 0, -250,85, 0, imagesx($stamp), imagesy($stamp));

// Output and free memory
                header('Content-type: image/png');
                imagepng($im);
                imagedestroy($im);

            }

        }
        $jungleproductlist=$temparray;

    }
    echo json_encode(@$jungleproductlist);

}


function jungleproductlist()
{
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $jungleproductlist = array();

    $queryu = db_select('jungleproduct', 'jp');
    $queryu->innerJoin('junglecategory', 'jc','jc.id=jp.category_id');
    $queryu->fields('jp');
    $queryu->fields('jc',array('cat_name'));
    if(isset($_POST['type']) && $_POST['type']!=''){
        $queryu->condition('jc.type',$_POST['type'],'=')  ;
    }

    if(@$_REQUEST['id']>0)$queryu->condition('jp.id',$_REQUEST['id'],'=')  ;

    $resultu = $queryu->execute();


    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {
            $temparray=$recordu;
            $temparray['textdesc']=strip_tags($recordu['product_desc']);

            $temparray['productlisturl'] = image_style_url('productlist', (@$recordu['product_file']));
            $temparray['productdetailmain'] = image_style_url('productdetailmain', (@$recordu['product_file']));
            $temparray['bestsellerp'] = image_style_url('bestseller', (@$recordu['product_file']));


            if($recordu['product_file']!='') {
                $productextns = explode('.', $recordu['product_file']);

                if ($productextns['1'] == 'mp4') {
                    $temparray['video_url'] = file_create_url(@$recordu['product_file']);;
                } else {
                    $temparray['image_url'] = image_style_url('front-photo_600_600_', (@$recordu['product_file']));
                }
            }

            if(@$_REQUEST['filter']>0)$jungleproductlist[@$recordu['id']]= $temparray;
                    else $jungleproductlist[$i]= $temparray;

            //echo $recordu['id'];
            $i++;
        }
    }
    echo json_encode(@$jungleproductlist,JSON_NUMERIC_CHECK);

}
function parentproductlist()
{
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $jungleproductlist = array();

    $queryu = db_select('jungleproduct', 'ca');
    $queryu->fields('ca');
    $queryu->condition('ca.parent_cat',0,'=');
    $resultu = $queryu->execute();


    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {
            $temparray=$recordu;


            $jungleproductlist[$i]= $temparray;
            $i++;

/*            $jungleproductlist[$i]['cat_name'] = $recordu['cat_name'];
            $jungleproductlist[$i]['id'] = $recordu['id'];
            $jungleproductlist[$i]['parent_cat'] = $recordu['parent_cat'];
            $jungleproductlist[$i]['status'] = $recordu['status'];
            $i++;*/

        }
    }
    // $records['user']=$userlist;




    echo json_encode(@$jungleproductlist);



}




function addjungleproduct(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $product_file='';
    if(isset($_POST['product_file']) && ($_POST['product_file']!='')){
        $product_file =$_POST['product_file'];
    }

    $query = db_insert('jungleproduct')->fields(array('product_name','product_desc','category_id','product_file','status','priority','price'));
        //foreach ($values as $record) {
        $query->values(array(@$_POST['product_name'],@$_POST['product_desc'],@$_POST['category_id']['id'],$product_file,1,@$_POST['priority'],@$_POST['price']));
        //}
        $query->execute();


    $data['status'] = 'success';
     echo json_encode($data);
    return;
}
function jungleproductupdates(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $product_file='';
    if(isset($_POST['product_file']) && ($_POST['product_file']!='')){
        $product_file =$_POST['product_file'];
    }


    db_update('jungleproduct')
        ->fields(array('product_name'=>@$_POST['product_name'],'product_desc'=>@$_POST['product_desc'],'category_id'=>@$_POST['category_id']['id'],'product_file'=>@$_POST['product_file'],'priority'=>@$_POST['priority'],'price'=>@$_POST['price']))
        ->condition('id', intval($_POST['id']))
         ->execute();
}



function deletejungleproduct(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $num_deleted = db_delete('jungleproduct')
        ->condition('id', @$_POST['id'])
        ->execute();

}

function jungleproductupdatestatus(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $status=1-intval($_POST['status']);
    $query=db_update('jungleproduct')
        ->fields(array('status'=>@$status))
        ->condition('id', intval($_POST['id']))
        ->execute();

    echo "true";
}



function filedownload(){
    ini_set('memory_limit', '128M');

    header('Content-type: text/html');
    //header('Content-Disposition: attachment');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

     $filePath = ('http://admin.jungledrones.com/sites/default/files/styles/front-photo_600_600_/public/1458148736_1460724758.png');

     $x=arg();
     //print_r($x); exit;	

     $queryu = db_select('jungleproduct', 'ca');
    $queryu->fields('ca');
    $queryu->condition('ca.id',$x[2],'=');
    $resultu = $queryu->execute();


    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {
            $temparray=$recordu;
            //$filePath = image_style_url('front-photo_600_600_', (@$recordu['product_file']));
            $filePath = @$recordu['product_file'];
            $filePath2 = @$recordu['product_file'];


            $jungleproductlist[$i]= $temparray;
            $i++;

/*            $jungleproductlist[$i]['cat_name'] = $recordu['cat_name'];
            $jungleproductlist[$i]['id'] = $recordu['id'];
            $jungleproductlist[$i]['parent_cat'] = $recordu['parent_cat'];
            $jungleproductlist[$i]['status'] = $recordu['status'];
            $i++;*/

        }
    }


    $filetype=explode('/',file_get_mimetype($filePath2));

    //print_r($filetype); exit;

    $queryu = db_select('image_styles', 'u');
    //$queryu->join('admin', 'f', 'f.user_id = u.uid');
    //$queryu->leftjoin('users_roles', 'ur', 'ur.uid = u.uid');
    //$queryu->fields('ur', array('rid'));
    $queryu->fields('u', array( 'name', 'isid'));
    //$queryu->fields('f', array('fname', 'lname', 'phone_no', 'mobile_no', 'address'))
    // ->condition('u.name', '%' . db_like('john') . '%', 'LIKE')
    $queryu->condition('u.isid', $x[3], '=');
    //$queryu->orderBy('u.ieid','DESC');
    //->condition('u.uid', 74, '=');
    $queryu->range(0, 1);
    $resultu = $queryu->execute();
    $recordu = $resultu->fetchAssoc();

    //print_r(($recordu['name']));
    //exit;
    $filePath = image_style_url($recordu['name'], (@$filePath));

    //echo strpos($filePath,'itok');
   // echo substr($filePath,0,strpos($filePath,'itok')-1);
   // exit;
    //exit;

     //file_transfer($filePath, array('Content-disposition', 'attachment; filename='.$filePath));
drupal_add_http_header('Content-disposition', 'attachment; filename=' .substr($filePath,0,strpos($filePath,'itok')-1));
    readfile($filePath);
  


    //file_download($filePath);
    /*print_r($filePath);

    if(file_exists($filePath)) {
        $fileName = basename($filePath);
        $fileSize = filesize($filePath);

        // Output headers.
        header("Cache-Control: private");
        header("Content-Type: application/stream");
        header("Content-Length: ".$fileSize);
        header("Content-Disposition: attachment; filename=".$fileName);

        // Output file.
        readfile ($filePath);
        exit();
    }
    else {
        die('The provided file path is not valid.');
    }*/
}





